services:
  app:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        DEBUG: ${DEBUG}
        ALLOWED_HOSTS: ${ALLOWED_HOSTS}
        TMDB_API_KEY: ${TMDB_API_KEY}
    ports:
      - "80:80"
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    networks:
      - default

networks:
    default: {}